version: '3.8'
services:
  db:
    image: postgres:14-alpine
    restart: always
    build: ./db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rocketdb
    ports:
      - '5432:5432'
    volumes: 
      - ./data:/data